### PR TITLE
Protobuf 3.19.6

### PR DESCRIPTION
**Pull request by sh-shahrokhi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@sh-shahrokhi, as with https://github.com/conda-forge/libprotobuf-feedstock/pull/152#issuecomment-1510199515, could you rebase this branch onto `v3.19.x` that I just created?  We don't want to merge it into `main`.

**Comment by sh-shahrokhi** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sh-shahrokhi, you'll need to rebase and take out all the commits you didn't make.  Rerendering isn't the primary problem right now.  If you prefer, it might be easier to start fresh like you did with `libprotobuf`.

**Comment by sh-shahrokhi** [comment]
> @conda-forge-admin, please rerender

ok, will do this

**Pull request closed without merging**
