### PR TITLE
add the cpp implementation to windows

### PR DESCRIPTION
**Pull request by carlodri**
following the instructions here: https://github.com/protocolbuffers/protobuf/tree/master/python

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin rerender

**Comment by carlodri** [comment]
sorry for this PR, it is not necessary, I was missing to set the environment variable `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp`, which enabled the C++ mode, at least according to https://stackoverflow.com/questions/39079065/tensorflow-check-which-protobuf-implementation-is-being-used

**Comment by carlodri** [comment]
re-opened due to #133

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by jakirkham** [comment]
Have pushed some changes to update this with the current state of things in `main`. Hope that is ok 🙂

**Comment by jakirkham** [comment]
The Windows builds fail with some variation of this error. This particular snippet taken from [this log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=486316&view=logs&j=7df5a329-fcdb-5857-5720-a5dae94c0641&t=428acfd7-2921-5219-037f-9169d136e406 ):

```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:../src/.libs /LIBPATH:D:\bld\protobuf_1649133564231\_h_env\libs /LIBPATH:D:\bld\protobuf_1649133564231\_h_env /LIBPATH:D:\bld\protobuf_1649133564231\_h_env\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64" /LIBPATH:D:\bld\protobuf_1649133564231\_h_env\Library\lib /LIBPATH:D:\bld\protobuf_1649133564231\_h_env\Library\lib protobuf.lib /EXPORT:PyInit__message build\temp.win-amd64-3.9\Release\google/protobuf/pyext\descriptor.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\descriptor_containers.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\descriptor_database.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\descriptor_pool.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\extension_dict.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\field.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\map_container.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\message.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\message_factory.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\message_module.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\repeated_composite_container.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\repeated_scalar_container.obj build\temp.win-amd64-3.9\Release\google/protobuf/pyext\unknown_fields.obj /OUT:build\lib.win-amd64-3.9\google\protobuf\pyext\_message.cp39-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.9\Release\google/protobuf/pyext\_message.cp39-win_amd64.lib
  LINK : fatal error LNK1181: cannot open input file 'protobuf.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe' failed with exit code 1181
  error: subprocess-exited-with-error
```

Have [attached the logs]( https://github.com/conda-forge/protobuf-feedstock/files/8414958/logs_486316.zip ) for posterity.

It is worth noting that the library names are prefixed with `lib` on Windows (so `libprotobuf.lib`) whereas the error mentions `protobuf.lib` cannot be found, which traces back to [here]( https://github.com/protocolbuffers/protobuf/blob/1ac05394a59f5132f0b14a589851a76d627e32f3/python/setup.py#L231 ). So there may be a filename discrepancy here.

**Comment by jakirkham** [comment]
Tried hacking around name issue by copying the `.lib` file to the expected name. That sort of worked since the linker found it, but then there were issues resolving symbols. Anyways this will probably require someone with a Windows machine to do more digging (which has been my experience with this issue before).

**Comment by h-vetinari** [comment]
I got this to work in #152 🙃

**Pull request merged**
