### PR TITLE
Protobuf 3.19.6

### PR DESCRIPTION
**Pull request by sh-shahrokhi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sh-shahrokhi** [comment]
@conda-forge-admin, please rerender

**Comment by sh-shahrokhi** [comment]
@xylar could you please help with this error in CI?
`conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-ppc64le: {MatchSpec("libprotobuf=3.19.6")}`

**Comment by sh-shahrokhi** [comment]
@conda-forge-admin, please rerender

**Comment by sh-shahrokhi** [comment]
@xylar , please check this one. it passed the tests. thank you.

**Comment by xylar** [comment]
Looks good.  I'm glad you figure out that patch.

**Pull request merged**
