### PR TITLE
protobuf 4.25.1

### LINKED ISSUE #210: Protobuf 25.0 and 25.1 missing
Version 25.0 and 25.1 have been released and are on PyPI but not here: https://github.com/protocolbuffers/protobuf/releases, https://pypi.org/project/protobuf/#history

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #210

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
I didn't see any indication that dependencies (other than obviously `libprotobuf`) had changed between 4.24.3 and 4.25.1.  But I would certainly welcome someone else having a look in case I missed something.

**Review by xhochy — APPROVED** [review]

**Comment by xylar** [comment]
Thanks very much, @xhochy.

**Comment by h-vetinari** [comment]
No it doesn't show up as 21.2, it's just that protobuf's versioning scheme is confusing, and also confusing our infrastructure.

21.2 is _exactly_ the same as 3.21.2 and the current 25.1 is _exactly_ the same as 4.25.1.

**Comment by h-vetinari** [comment]
See also #181 and #182

**Pull request merged**
