### PR TITLE
Update to 3.20.3

### PR DESCRIPTION
**Pull request by sh-shahrokhi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Dependencies from https://github.com/conda-forge/libprotobuf-feedstock/pull/148 should be available in a few hours.  I'll rerender and start CI then.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sh-shahrokhi, I hope you don't mind that I marked this as ready for review.

**Comment by xylar** [comment]
@sh-shahrokhi, thanks very much for taking the initiative on this!

**Comment by sh-shahrokhi** [comment]
> @sh-shahrokhi, thanks very much for taking the initiative on this!

do you know why it does not show up in conda-forge? I am using python=3.10

**Comment by sh-shahrokhi** [comment]
Could not solve for environment specs
The following packages are incompatible
└─ protobuf 3.20.3**  is installable with the potential options
   ├─ protobuf 3.20.3 would require
   │  └─ libprotobuf 3.20.3.* , which can be installed;
   ├─ protobuf 3.20.3 would require
   │  └─ python >=3.11,<3.12.0a0 , which can be installed;
   ├─ protobuf 3.20.3 would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   └─ protobuf 3.20.3 would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.

**Comment by xylar** [comment]
It will take awhile.

**Comment by xylar** [comment]
This worked for me:
```
mamba create -y -n test protobuf=3.20.3 python=3.10
```
so I think the package is tere now.

**Comment by xylar** [comment]
@sh-shahrokhi, if you're still having trouble, please post the full command you're running.

**Pull request merged**
