### PR TITLE
protobuf 5.26.1

### PR DESCRIPTION
**Pull request by h-vetinari**
This is going to be a bigger operation I fear - just opening this PR as a status update for now. Protobuf [removed](https://github.com/protocolbuffers/protobuf/commit/5722aeffcad72e9a335a3ec7985858dfa31477be) the usual `setup.py` approach, and we now either need to deal with the PyPI sources (harder to patch) or build with bazel.

Also, the new [way](https://github.com/protocolbuffers/protobuf/blob/v26.1/python/dist/setup.py) to build python from source seems to just rebuild a lot of stuff we already have in [libprotobuf](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibprotobuf-5.26.1-h08a7969_0.conda) (e.g. `utf8_range`), and more importantly, also `upb`, which is also being vendored by grpc, causing potential clashes there. I had tried to avoid this in https://github.com/protocolbuffers/protobuf/issues/12927 but to no avail (c.f. also #170).

The C++ backend is also removed, so I guess it's not even possible anymore to build atop of `libprotobuf`.

### CODE REVIEW

**Comment by h-vetinari** [comment]
After discussion in https://github.com/conda-forge/bazel-feedstock/pull/240 & 1:1, @xhochy proposed we use the stand-alone bazel from upstream here; currently trying to figure out how that might work.

**Comment by xhochy** [comment]
ppc64le depends on https://github.com/conda-forge/bazel-toolchain-feedstock/pull/20

**Comment by xhochy** [comment]
Running into https://github.com/bazelbuild/bazel/issues/18683 and https://github.com/protocolbuffers/protobuf/issues/12947 now.

**Comment by h-vetinari** [comment]
Huge props for the work here! 💪 

> Running into [bazelbuild/bazel#18683](https://github.com/bazelbuild/bazel/issues/18683) and [protocolbuffers/protobuf#12947](https://github.com/protocolbuffers/protobuf/issues/12947) now.

They really did a number on us with the build backend change... Fingers crossed your heroics pay off!

**Comment by h-vetinari** [comment]
This is getting pretty far already (`[1,725 / 1,740]`)!

Not finding the python headers sounds like a comparatively simple problem... 😅 
```
D:\bld\bazel\execroot\com_google_protobuf\python/python_api.h(21): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
```

**Comment by xhochy** [comment]
> Not finding the python headers sounds like a comparatively simple problem... 😅

No , this is Bazel. Nothing is simple 🤪

**Comment by xhochy** [comment]
> 2024-09-18T09:34:00.9884605Z SUBCOMMAND: # //python:_message_binary [action 'Compiling python/unknown_fields.c', configuration: 0bcc95b30ab9b25a4dfbec7bcd268ba93a5586ee7cd24012848ff546252aecbf, execution platform: @local_config_platform//:host]
2024-09-18T09:34:00.9885339Z cd /d D:/bld/bazel/execroot/com_google_protobuf
2024-09-18T09:34:00.9886588Z   SET INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
2024-09-18T09:34:00.9890832Z     SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\DiagnosticsHub\Collector;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\;;C:\Windows\system32;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg
2024-09-18T09:34:00.9893616Z     SET PWD=/proc/self/cwd
2024-09-18T09:34:00.9894114Z     SET PYTHON_BIN_PATH=D:\bld\protobuf_1726649794067\_h_env\python.exe
2024-09-18T09:34:00.9894613Z     SET RUNFILES_MANIFEST_ONLY=1
2024-09-18T09:34:00.9895058Z     SET TEMP=C:\Users\VSSADM~1\AppData\Local\Temp
2024-09-18T09:34:00.9895542Z     SET TMP=C:\Users\VSSADM~1\AppData\Local\Temp
2024-09-18T09:34:00.9895985Z     SET VSLANG=1033
2024-09-18T09:34:00.9898205Z   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-fastbuild/bin /Iexternal/system_python /Ibazel-out/x64_windows-fastbuild/bin/external/system_python /Ibazel-out/x64_windows-fastbuild/bin/third_party/utf8_range/_virtual_includes/utf8_range /Ibazel-out/x64_windows-fastbuild/bin/src/google/protobuf/_virtual_imports/descriptor_proto /Iexternal/system_python/python /Ibazel-out/x64_windows-fastbuild/bin/external/system_python/python /DBAZEL_CURRENT_REPOSITORY="" /showIncludes /MD /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-fastbuild/bin/python/_objs/_message_binary/unknown_fields.obj /c python/unknown_fields.c

This looks like it doesn't use the `py_cc`  toolchain.

**Comment by h-vetinari** [comment]
Getting reeeeeeal close now
```
[1,737 / 1,740] Linking python/_message_binary.dll; 0s local
LINK : fatal error LNK1104: cannot open file 'python311.lib'
```

**Comment by xhochy** [comment]
image

🎉

**Comment by h-vetinari** [comment]
Spectacular work! ❤️🙏 

I was wondering how we can check that the `use_fast_cpp_protos` bits are working. According to the link check, both `libprotobuf` and `libabseil` are unused... Also we might want to double-check (not sure yet how) if the upb-symbols are actually made invisible by https://github.com/protocolbuffers/protobuf/pull/17207, because otherwise we'll get clashes with the upb in grpc.

**Comment by xhochy** [comment]
> According to the link check, both libprotobuf and libabseil are unused...

Yes, they are statically linked, and there is no system libs option. I would probably be able to build one, but I don't have the patience for this atm. We would have to copy what Tensorflow does over here.

**Comment by xhochy** [comment]
From my side, this is ready for a merge. @h-vetinari feel free to add what you want on top. There is at least one unit test that checks for `use_fast_cpp_protos`. I'm not sure though whether unit tests are an easy feast here.

**Comment by h-vetinari** [comment]
OK, I'm fine to merge this for now. We'll have to keep iterating anyway going forward. I'd also tend towards _not_ migrating 5.26, as that seems to have already been fully dropped upstream (i.e. 5.25, 5.27 & 5.28 receive patch releases, but not 5.26).

My preference would be to build 5.27.5 against the new abseil, bootstrap a recent grpc on top (1.66?), and then try for a migration. We can also discuss this in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075

**Comment by xhochy** [comment]
Then, I'll merge this and spent some time on migrating the patches for each release until we hit the newest. If we at one point still need an older release, we then have them.

**Comment by h-vetinari** [comment]
I don't think we need the older patch releases for 5.27.x; I think we could go directly for 5.27.5 from here, but if you wanna build out the whole line, go for it. At least the libprotobuf bits should be there already.

> Yes, they are statically linked, and there is no system libs option.

We might want to remove the run-deps here then for now

**Comment by h-vetinari** [comment]
oh well. 🙃

**Comment by xhochy** [comment]
We can remove them in a follow-up PR. Packages with smaller dependencies will be preferred.

**Comment by h-vetinari** [comment]
> We can remove them in a follow-up PR. Packages with smaller dependencies will be preferred.

I know, no big deal.

**Comment by h-vetinari** [comment]
Though we might want to still have a run-constraint? I guess we'd open ourselves up to some possibly weird interactions if we let the versions of `protobuf` and `protoc`/`libprotobuf` diverge in any given build/environment...?

**Pull request merged**
