### PR TITLE
Rebuild against last build of libprotobuf

### PR DESCRIPTION
**Pull request by JohanMabille**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is on the path to fix https://github.com/conda-forge/arcticdb-feedstock/pull/88

### CODE REVIEW

**Comment by JohanMabille** [comment]
@conda-forge-admin please rerender

**Comment by JohanMabille** [comment]
Oh, so we need to rebuild grpcio-tools only ?

**Comment by h-vetinari** [comment]
> Oh, so we need to rebuild grpcio-tools only ?

That would be my first try. Rebuild grpcio-tools for 1.58. This PR changes nothing vis-à-vis the builds that already exist for 4.24.3

**Comment by JohanMabille** [comment]
Then I think I need you to create a branch for 1.58 on https://github.com/conda-forge/grpc-cpp-feedstock

**Comment by JohanMabille** [comment]
Actually let's drop the build of ArcticDB on OSX Python 3.8, that would pkae our lives easier.

**Comment by h-vetinari** [comment]
> Then I think I need you to create a branch for 1.58 on https://github.com/conda-forge/grpc-cpp-feedstock please ;)

I already did, I just haven't pushed it yet.

**Pull request closed without merging**
