### PR TITLE
Windows CPP builds

### PR DESCRIPTION
**Pull request by h-vetinari**
This feedstock's fallen behind a bit, but before catching up, I wanted to see if I can revive #132

### CODE REVIEW

**Comment by h-vetinari** [comment]
protobuf has a particular predilection for doing everything statically. In this case, we'll definitely need to strip the `/MT` part from the invocation which is currently superseding `/MD`.

**Comment by h-vetinari** [comment]
> Do you mind if I get the latest releases merged first and we make these changes later?

Not at all, please go ahead!

> Or do you think you're on the verge of getting it to work?

I'd have to dig into the build scripts to find out (at least) where the `/MT` is being added from, and I haven't had time for that.

**Comment by h-vetinari** [comment]
Should be cleaner to switch to `libprotobuf-static` after the changes in https://github.com/conda-forge/libprotobuf-feedstock/pull/128.

**Comment by h-vetinari** [comment]
@conda-forge/protobuf PTAL
Windows CPP integration is working now 🥳

**Review by xylar — APPROVED** [review]
That's awesome, @h-vetinari!

**Comment by xylar** [comment]
I'm going to go ahead and merge.

**Comment by carlodri** [comment]
Great work @h-vetinari, thanks!

**Pull request merged**
