### PR TITLE
Update to protobuf v22.0.

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Updating to a new version: https://github.com/protocolbuffers/protobuf/releases/tag/v22.0

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Not really any point in doing this here until https://github.com/conda-forge/libprotobuf-feedstock/pull/145 goes in.

**Comment by xylar** [comment]
But you're welcome to get a head start.

**Comment by bdice** [comment]
Ah, thanks @xylar. I wasn't familiar with how this was packaged. Let me know if I can help with anything.

**Comment by xylar** [comment]
It looked like @h-vetinari had a pretty hard go at getting rc2 to work here https://github.com/conda-forge/libprotobuf-feedstock/pull/144, seemingly without quite succeeding.  I imagine it'll be a little time before we can update.

**Comment by h-vetinari** [comment]
See https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4075. I'm trying to do abseil first, then grpc, then protobuf. Protobuf will be trickier than usual due to an API/ABI break (new major number). The issues in the PR are solvable, but currently lower priority than shepherding the other migrations. Abseil is currently intertwined with re2 and segfaulting on arrow, where I'll likely need some upstream help. Untangling all of this will take some time, I'm afraid.

**Comment by bdice** [comment]
Closing in favor of #186. Thanks @h-vetinari for the effort here.

**Pull request closed without merging**
