### PR TITLE
protobuf v23.4

### PR DESCRIPTION
**Pull request by JanuszL**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by JanuszL** [comment]
<code>@<space/>conda-forge-admin, please rerender</code>

**Comment by JanuszL** [comment]
Relates to https://github.com/conda-forge/libprotobuf-feedstock/pull/171

**Comment by h-vetinari** [comment]
Thanks for the PR! This is not how this works though... 😅 

Aside from that, I'm going to hold off on merging further abseil PRs until I can get a decision about bumping the MacOS requirement conda-forge wide to 10.13 (otherwise abseil doesn't work). What you could do here is raise a PR that bumps this feedstock to 4.23.4, of which we also have a build for the previous abseil version. :)

**Comment by JanuszL** [comment]
> What you could do here is raise a PR that bumps this feedstock to 4.23.4, of which we also have a build for the previous abseil version. :)

Done. I hope it compiles without any problems.

**Comment by h-vetinari** [comment]
> Done. I hope it compiles without any problems.

It will fail pretty much right away 🙃 

But it's easy to fix: you need to update the expected hash for `https://github.com/protocolbuffers/protobuf/archive/refs/tags/v{{ version }}.tar.gz`.

You can wait to see the right one in the CI logs, but personally I do:
```
curl -L https://github.com/protocolbuffers/protobuf/archive/refs/tags/v23.4.tar.gz | sha256sum
```

**Comment by JanuszL** [comment]
> > Done. I hope it compiles without any problems.
> 
> It will fail pretty much right away 🙃
> 
> But it's easy to fix: you need to update the expected hash for `https://github.com/protocolbuffers/protobuf/archive/refs/tags/v{{ version }}.tar.gz`.
> 
> You can wait to see the right one in the CI logs, but personally I do:
> 
> ```
> curl -L https://github.com/protocolbuffers/protobuf/archive/refs/tags/v23.4.tar.gz | sha256sum
> ```

Thank you again for help. Done.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Review by h-vetinari — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
