### PR TITLE
update 3.5.0

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/google/protobuf/releases/tag/v3.5.0

### CODE REVIEW

**Comment by Maltimore** [comment]
Would be great to merge this soon as with the current tensorflow (1.4.0), protobuf 3.4 is not sufficient and results in weird errors.

**Comment by jakirkham** [comment]
What errors @Maltimore?

**Comment by Maltimore** [comment]
@jakirkham I was getting import errors. As I was playing around with different versions (of combinations of tensorflow, tensorflow-gpu, keras and protobuf), there were different import errors, but one I recorded was:

KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"

Is this error not reproducible for you? Installing tensorflow and tensorflow-gpu 1.4.0 and protobuf 3.4 should reproduce it.

**Comment by hajapy** [comment]
Are you sure that's not because you have both tensorflow and tensorflow-gpu installed? AFAIK, you should not have both of these installed at the same time. Try uninstalling them both and re-installing just one and let us know if you still have issues with protobuf 3.4.

**Comment by Maltimore** [comment]
Interesting question. I'll try it out and get back to you ASAP.

**Pull request merged**
