### PR TITLE
Update to version 3.6.0

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by hajapy** [comment]
Consider removing the fix for the init files, that is fixed upstream afaik.

**Comment by hajapy** [comment]
Looks like build failures are due to https://github.com/google/protobuf/pull/4930, which are fixed in master but not in protobuf 3.6.0, 3.6.0.1, 3.6.1

We should consider patching setup.py with https://github.com/google/protobuf/commit/c7e0e262a6a9ccbfd1f19aed306be8986073ab83#diff-8cf6167d58ce775a08acafcfe6f40966

**Comment by jjhelmus** [comment]
> Consider removing the fix for the init files, that is fixed upstream afaik.

Done



> We should consider patching setup.py with google/protobuf@c7e0e26#diff-8cf6167d58ce775a08acafcfe6f40966

I tried applying that patch but it did not seem to resolve the issue.  Adding `--std=c++11` directly to CFLAGS seems likes a work around.

**Comment by hajapy** [comment]
There is an init fix is the windows bld.bat file as well that could be removed. 

Happy with the CFLAGS approach as well.

**Pull request merged**
