### PR TITLE
[v4.23.x] Reinstate PyPy

### PR DESCRIPTION
**Pull request by h-vetinari**
Let's try again

### CODE REVIEW

**Comment by h-vetinari** [comment]
```
import: 'google.protobuf.pyext._message'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/protobuf_1695848863394/test_tmp/run_test.py", line 17, in <module>
    import google.protobuf.pyext._message
TypeError: type 'google.protobuf.pyext._message.DescriptorBase' is not an acceptable base type
```

Not sure what to make of this TBH

**Comment by mattip** [comment]
Can you restart CI? I think the new PyPy release should fix that error.

**Comment by h-vetinari** [comment]
Done 🤞

**Comment by mattip** [comment]
... and CI is passing.

**Pull request merged**
